[general]
import = ["rasmus.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "Iosevka Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 0

[terminal.shell]
program = "zellij"
args = ["attach", "--create", "main"]

[window]
decorations = "none"
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 2
y = 2
